fine, I'll do it myself. - add snoo.habedieeh.re and onion version
ferritreader/ferrit-instances pull request #4
Opened 2022-10-22 07:24 UTC by shruuub

2022-10-22 18:56 UTC, Daniel-Valentine requested changes

2022-10-22 18:56 UTC, Daniel-Valentine commented on instances.json
> -      "i2p": "http://vernchoyi4qjf6sz5vi57sskoelw5lsf53u62i5uvktzpa6sxv3a.b32.i2p",
I don't think we want to get rid of this. Did you run your update script with an I2P router running?

2022-10-23 07:13 UTC, shruuub commented on instances.json
> -      "i2p": "http://vernchoyi4qjf6sz5vi57sskoelw5lsf53u62i5uvktzpa6sxv3a.b32.i2p",
huh, I did not. From the readme and the script's output it seemed like it would just be skipped

2022-10-23 07:17 UTC, shruuub commented on instances.json
> -      "i2p": "http://vernchoyi4qjf6sz5vi57sskoelw5lsf53u62i5uvktzpa6sxv3a.b32.i2p",
Okay, so I just added it via the gh web editor (hope that doesnt break things with json and stuff). Sorry for the inconvenience.
_btw the pr message wasn't meant to be mean if it seems that way, just doing the funny_

2022-10-23 07:42 UTC, Daniel-Valentine requested changes

2022-10-23 07:42 UTC, Daniel-Valentine commented on instances.json
> +    }
```suggestion
    },
```

2022-10-23 07:43 UTC, Daniel-Valentine commented on instances.json
> -      "i2p": "http://vernchoyi4qjf6sz5vi57sskoelw5lsf53u62i5uvktzpa6sxv3a.b32.i2p",
No worries. I did not take offense. I'll also edit the README to clarify that onion/i2p sites are all or nothing updates.

2022-10-23 07:45 UTC, merged